Update build script

diff --git a/.github/workflows/build-deploy-azure.yml b/.github/workflows/build-deploy-azure.yml
--- a/.github/workflows/build-deploy-azure.yml
+++ b/.github/workflows/build-deploy-azure.yml
@@ -35,7 +35,16 @@ jobs:
         run : npx tslint src/**/*.ts
 
       - name: Run build
-        run : npm run build:prod --output-path=/dist
+        run : npm run build:prod
+
+      - name: check if dist folder exists
+        run: |
+          if [ -d "dist" ]; then
+            echo "Directory dist exists."
+          else
+            echo "Error: Directory dist does not exists."
+            exit 1
+          fi
 
 
       - name: Deploy to azure static web apps
@@ -46,11 +55,6 @@ jobs:
           repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
           action: "upload"
           skip_app_build: true # Set this to true if you do not want to build the app before deploying.
-          skip_api_build: true # Set this to true if you do not want to build the api before deploying.
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
-          app_location: "/dist" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "" # Built app content directory - optional
-          ###### End of Repository/Build Configurations ######
+          app_location: "dist" # App source code path
+
 
